services:
  docker-wolfi-nextjs-s3:
    container_name: docker-wolfi-nextjs-s3
    user: "${USER_ID}:${USER_ID}"  

    command: ["sh", "-c", "node ./node_modules/pm2/lib/binaries/CLI.js start ecosystem.config.js"]
    # debug
    # command: ["sh", "-c", "node ./node_modules/pm2/lib/binaries/CLI.js start ecosystem.config.js --no-daemon"]
    # command: ["node", "next-server.js"]
    image: "docker-wolfi-nextjs-s3"
    build:
      context: .
      args:
        - PORT=$PORT
        - CONTAINER_SHARED_PATH=${CONTAINER_SHARED_PATH}
        - USER_ID=${USER_ID}
    volumes:
      - ${PWD}/../${CONTAINER_SHARED_PATH}:/app/${CONTAINER_SHARED_PATH}
    ports:
      - "$PORT:$PORT"
